- name: Remove Docker Swarm from all nodes
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Leave Docker Swarm
      command: docker swarm leave --force
      register: leave_output
      ignore_errors: false

    - name: Print Swarm leave output
      debug:
        msg: '{{ leave_output.stdout }}'

- name: Cleanup Swarm Data on Manager Nodes
  hosts: managers
  become: true
  become_user: root
  tasks:
    - name: Remove swarm data directory
      command: rm -rf /var/lib/docker/swarm
