- name: Git Lab parameters
  hosts: all
  tasks:
    - name: Debug Git Lab parameters
      debug:
        msg:
          - 'email: {{ email }}'
          - 'password: {{ password }}'
          - 'host: {{ host }}'

- name: Deploy Docker Compose Application
  hosts: all
  become: true # Use sudo if necessary
  become_user: root
  tasks:
    # Step 1: Ensure Docker is installed (optional)
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    # Step 2: Ensure Docker Compose is installed (optional)
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Create directory for Docker Compose files
      file:
        path: /opt/docker-compose
        state: directory
        mode: '0755'
        owner: root
        group: root

    # Step 3: Copy Docker Compose file to the target machine
    - name: Copy Docker Compose file
      copy:
        src: files/docker-compose.yml.j2
        dest: /opt/docker-compose/docker-compose.yml

    # Step 4: Run Docker Compose
    - name: Run Docker Compose
      community.docker.docker_compose:
        project_src: /opt/docker-compose/
        state: present # Options: present, absent, or restarted
      environment:
        EMAIL: '{{ email }}'
        PASSWORD: '{{ password }}'
        HOST: '{{ host }}'
        HOST_URL: '{{ hosturl }}'
