- name: Upgrade all apt packages
  hosts: all
  become: true
  tasks:
    - name: Remove apt lock files
      command: rm -f /var/lib/apt/lists/lock /var/cache/apt/archives/lock /var/lib/dpkg/lock-frontend

    - name: Reconfigure dpkg
      command: dpkg --configure -a

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
