version: '3.8'

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - CI_SERVER_URL=https://hosturl
      - RUNNER_EXECUTOR=docker
      - DOCKER_PRIVILEGED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner

volumes:
  gitlab-runner-config:
